### ISSUE TITLE
Unable to add the BAASBox.Access to Visual Studio

### ISSUE THREAD

**Issue by arsanjea** [instantiator/BAASBox.Access#1]
I get the following problem:

Could not install package 'Microsoft.Bcl.Build 1.0.14'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v5.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.         0

**Comment by instantiator** [comment]
Hi - I have some serious updates to make to this project. Thanks for raising the issue - I'll get back to you when it's done.

**Comment by arsanjea** [comment]
Great! I'm planning on using BAASBox with Xamarin on Friday, let me know if
you can release something by then... :)

**Comment by JDSlimz** [comment]
Has this been rectified yet? I would like to use this library for an app I am building. When I try to install I get the following error:

`Could not install package 'Microsoft.Bcl.Build 1.0.14'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by instantiator** [comment]
Thanks for this - I'm sorry to say that I'm closing this project. It was fun to work on, but ultimately I wasn't able to dedicate enough time to it. I believe there are other BAASBox SDK frameworks available, and I recommend you take a look at them...

Here's one. Although I note it hasn't been update for ~3 years it may well still be in working condition:
https://github.com/OlexaLe/BaasBoxNetSDK

BAASBox itself provides a decent, well documented, JSON web API, so you may simply decide to implement that yourself.
